triSYCL/triSYCL

- include/CL/sycl/device.hpp
implicitly specifying the return type of get_info by using 'auto', seems to solve compiler issues.
> BUG FIX: size_t -> auto in sycl/device.hpp

- include/CL/sycl/detail/small_array.hpp
- tests/vector/vecacc.cpp
accessors x and y are needed by the SyclParallelSTL
accessors x, y and z are necessary if we use vec to implement cl_float3
> add accessors x, y, z to small_array

- tests/examples/CMakeLists.txt
Build was failing because a previous commit removed  the demo_parallel_matrices_add example source file without removing it's build target.
> Remove reference to deleted test

- .travis.yml
- Dockerfile
- README.rst
- Enable build with clang-4 and gcc-6 with or without OpenCL or OpenMP
- Use POCL as the OpenMP implementation
- Add the travis-ci build icon in the README
- Configure Docker to build the right branch depending on the origin of the build (commit or pull request)
> Improve Travis-CI build 

- include/CL/sycl/buffer.hpp
- include/CL/sycl/buffer/detail/buffer.hpp
- tests/buffer/buffer_unique_ptr.cpp
This should fix https://github.com/triSYCL/triSYCL/issues/48
Also remove buffer construction from a std::unique_ptr according to latest SYCL specification, since the std::shared_ptr constructor is enough.
> Fix compilation issue with GCC 7.1 & Clang with libc++

- include/CL/sycl/detail/default_classes.hpp
Made hash_class be a member of cl::sycl. Implement for issue #69
> Add alias for std::hash<T>

- include/CL/sycl/group.hpp
- include/CL/sycl/parallelism/detail/parallelism.hpp
- tests/address_spaces/address_spaces_pstl.cpp
- tests/group/group.cpp
- tests/jacobi/include/stencil-fxd.hpp
- tests/jacobi/include/stencil-gen-var.hpp
- tests/jacobi/include/stencil-var.hpp
- tests/multiple_compilation_units/parallel_for.cc
- tests/parallel_for/hierarchical.cpp
- tests/parallel_for/hierarchical_new.cpp
> Rename SYCL 1.2 member function group::get() to SYCL 1.2.1 group::get_id()

- cmake/FindTriSYCL.cmake
Fix a small typo ("COMPILIER") that breaks the MSVC compiler detection in FindTriSYCL.cmake
> Fix typo in CMake MSVC detection

- .travis.yml
- Dockerfile
Since support of 17.04 Zesty Zapus just stopped on January 13, 2018
and broke the triSYCL CI, take the opportunity to use more recent
compiler versions too.
> Update Travis CI to Ubuntu 17.10, GCC 7 and Clang 5.0

- tests/pipe/pipe_observers.cpp
This fixes:
ome/airlied/devel/compute/trisycl/tests/pipe/pipe_observers.cpp: In instantiation of ‘<lambda(auto:5&, cl::sycl::pipe&)> [with auto:5 = cl::sycl::queue]’:
/home/airlied/devel/compute/trisycl/tests/pipe/pipe_observers.cpp:69:3: required from here
/home/airlied/devel/compute/trisycl/tests/pipe/pipe_observers.cpp:48:11: error: passing ‘const cl::sycl::accessor<bool, 1, (cl::sycl::access::mode)43, (cl::sycl::access::target)2014>’ as ‘this’ argument discards qualifiers [-fpermissive]
v = p.METHOD();
^~
/home/airlied/devel/compute/trisycl/tests/pipe/pipe_observers.cpp:56:1: note: in expansion of macro ‘MAKE_GET_OBSERVER’
MAKE_GET_OBSERVER(empty, bool);
^~~~~~~~~~~~~~~~~
In file included from /home/airlied/devel/compute/trisycl/include/CL/sycl.hpp:37,
from …
> pipe_observers: add const to the pipe write accessor

- .travis.yml
- Dockerfile
- doc/architecture.rst
- tests/Makefile
- tests/pipe/pipe_observers.cpp
Now there is more and more C++17 features in triSYCL, switch to latest
Ubuntu version and compilers.
> Update Travis CI to Ubuntu 18.04, GCC 8 and Clang 6.0

- include/CL/sycl.hpp
- include/CL/sycl/device_selector.hpp
- include/CL/sycl/device_selector/detail/device_selector_tail.hpp
- include/CL/sycl/half.hpp
- include/CL/sycl/platform.hpp
- include/CL/sycl/platform/detail/host_platform.hpp
- include/CL/sycl/platform/detail/host_platform_tail.hpp
- include/CL/sycl/platform/detail/opencl_platform.hpp
- include/CL/sycl/platform/detail/opencl_platform_tail.hpp
- include/CL/sycl/platform/detail/platform.hpp
- include/CL/sycl/platform/detail/platform_tail.hpp
- include/CL/sycl/program.hpp
- include/CL/sycl/program/detail/program.hpp
This series allows trisycl to build the cts test_device_selector and execute it.
It unfortunately has to add a dummy half implementation and some basic bits of the program object, in order just to get the CTS common code to compile. Otherwise it fixes up the platform and device_selector code.
Feel free to request any and every change in this, my C++ is definitely naive in some places, and I think the last patch might need more experience C++ eyes on it for what is necessary or a cleaner way to do it.
> implement  select device

- include/CL/sycl/opencl_types.hpp
- tests/vector/cl_types.cpp
This is my first (maybe 20th I did locally) go at fixing the scalar types when we aren't using OPENCL.
When I moved some of the size_t to cl_ulong in the later patches, the local tests start failing (when built without OPENCL) because it couldn't cast vec<cl_ulong,1> to size_t when it really should have been cl_ulong to size_t.
The test fix is a little messier, but I ran into a lot of BOOST_PP problems with commas and didn't dig my way out for a few hours, this was the best compromise I came up with that built and passed the tests.
> types: fix non-opencl scalar types to not be vectors

- include/CL/sycl/device/detail/host_device.hpp
This should fix the ParallelSTL breakage
> device: set max_work_item_sizes for host.

- include/CL/sycl/group.hpp
- tests/group/group.cpp
Just one that was missed in the last set of these by the looks of it.
> group: rename get_linear->get_linear_id for SYCL 1.2.1 rev 3

- include/CL/sycl/buffer.hpp
- tests/2014-04-21-HPC-GPU_Meetup/slide_26.cpp
- tests/accessor/accessor.cpp
- tests/accessor/accessor_sizes.cpp
- tests/buffer/buffer_map_allocator.cpp
- tests/buffer/buffer_set_final_data_1.cpp
- tests/buffer/buffer_unique_ptr.cpp
- tests/buffer/shared_buffer.cpp
- tests/common/test-helpers.hpp
- tests/jacobi/jacobi2d-st-cplx-var.cpp
- tests/jacobi/jacobi2d-st-fxd.cpp
- tests/jacobi/jacobi2d-st-gen-var.cpp
- tests/jacobi/jacobi2d-st-var.cpp
- tests/jacobi/jacobi2d-tile.cpp
- tests/jacobi/jacobi2d.cpp
This must have changed in the spec, convert the constructor
to align with the spec to avoid the excess host_buffer.
This requires changes to a bunch of tests to align with the new API
> buffer: fix get_access to correspond to spec.

- include/CL/sycl/address_space.hpp
- include/CL/sycl/address_space/detail/address_space.hpp
- tests/address_spaces/address_spaces.cpp
- tests/address_spaces/address_spaces_ptr.cpp
This aligns the address space with the spec.
The 1.2.1 spec doesn't define generic at all, but I've left it
in for now.
> address_space: realign with spec.

- include/CL/sycl/accessor/detail/local_accessor.hpp
- include/CL/sycl/buffer/detail/buffer.hpp
- include/CL/sycl/range.hpp
- tests/accessor/accessor_sizes.cpp
- tests/buffer/buffer_sizes.cpp
- tests/range/range_size.cpp
The spec seems to have fixed size to mean get_count, and there
is no get_count. Update the implementation/tests.
> range: fix get_count->size rename.

- include/CL/sycl/buffer/detail/buffer_base.hpp
std::condition_variable requires the mutex be locked when
adjusting the variable even if the variable is atomic.
This should fix cases where the pipe_observers test would hang and stall CI.
> fix buffer release locking.

- include/CL/sycl/buffer/detail/buffer_base.hpp
- include/CL/sycl/pipe/detail/pipe.hpp
- include/CL/sycl/queue/detail/queue.hpp
Also apply some micro-optimization to unlock before std::condition_variable::notify_all().
This should close https://github.com/triSYCL/triSYCL/issues/37
>  Add a missing lock around the use of a std::condition_variable

- include/CL/sycl/group.hpp
- include/CL/sycl/h_item.hpp
- include/CL/sycl/item.hpp
- include/CL/sycl/nd_item.hpp
- include/CL/sycl/nd_range.hpp
- tests/group/CMakeLists.txt
- tests/group/group.cpp
- tests/item/CMakeLists.txt
- tests/item/item.cpp
- tests/nd_item/CMakeLists.txt
- tests/nd_item/nd_item.cpp
- tests/nd_range/CMakeLists.txt
- tests/nd_range/nd_range.cpp
These are all defined in the spec, so add == and != for
nd_range, group, item, nd_item and h_item.
This is based on the id operators #177 so should be applied after that one is sorted out.
> Add missing group/item comparison operators

- include/CL/sycl/vec.hpp
- include/CL/sycl/vec/detail/vec.hpp
This refactors the vector code so we have a detail vec base class,
then subclasses for each valid vector size.
It adds the specialised rgba, xyzw, Sx index entrypoints to each
specific subclass so only valid ones are available for each type.
> vec: move to a base class and specialise just for 1,2,3,4,8,16 vectors.

- tests/Makefile
Expand explicitly the header and library parameters.
> Update Makefile so that RTags .rtags target can work with gtkmm library

- tests/array_partition/array_partition.cpp
`windef.h` defines a symbol called SIZE in the global namespace, which conflicts with the definition here and causes a compile error. `windef.h` has no business defining that common a name in the global namespace, but we'll have to live with it and adjust our code around it.
Before this fix, compiling the tests on Windows using MinGW would result in the following error:
[ 17%] Building CXX object tests/array_partition/CMakeFiles/array_partition_array_partition.dir/array_partition.cpp.obj
C:\Persoonlijk\Projecten\Libraries\triSYCL\tests\array_partition\array_partition.cpp:19:18: error: 'constexpr const size_t SIZE' redeclared as different kind of symbol
constexpr size_t SIZE = 4;
^~~~
In file included from C:/PROGRA~1/MINGW-~1/X86_64~4.0-P/mingw64/x86_64-w64-mingw32/include/windows.h:69, …
> Fix naming conflict with windef.h

- cmake/FindTriSYCL.cmake
This has been disabled since the first CMake scripts in commit 7d6b30d74cfed2ef0a6e0bf1a9c90539cbe83b93.
Trying to compile anything using TriSYCL on Windows with OpenMP enabled causes a linker error. Removing this check causes it to link properly.
I believe we have two options to fix it: Either cause OpenMP on Windows to always fail in CMake's configure stage, or link it properly. This implements the second option! If there were good reasons to not link OpenMP on Windows, then we could also implement the former.
Fixes one of the two errors outlined in #201.
> Link OpenMP on Windows

- cmake/FindTriSYCL.cmake
Boost::compute depends on Boost::filesystem when compiling with its offline cache, according to [the documentation](https://boostorg.github.io/compute/boost_compute/getting_started.html). We must also link Boost::filesystem in order to compile a project with TriSYCL.
This fixes one of the two errors reported in #201. This can be seen to go wrong by compiling TriSYCL itself, where it goes wrong in some of the tests.
> Link to Boost::filesystem

- tests/Makefile
Modifying the bitcode compile step to swap around the global dead code elimination step. Having it in-front of inSPIRation was letting the gxx personality function through. Also commenting out the -reqd-workgroup-size-1 pass until the main branch is synced up to use it!
> Modifying the bitcode compile step

- include/CL/sycl/detail/global_config.hpp
- include/CL/sycl/device_runtime.hpp
Removing the static storage for cl_programs when compiling using SDx for 
the Xilinx runtime.
This relates to issue 145: https://github.com/triSYCL/triSYCL/issues/145
> Remove limitation on number of programs managed by triSYCL

- doc/environment.rst
- tests/Makefile
Modfying the previous Xilinx_SDK .bin generation step which output a PK
binary file to a newer method that outputs an xclbin binary that the XRT
runtime seems to accept for the moment for sw_emu and hw_emu.
Also adding some missing/new clean steps to support the new generation
steps.
Adding environment variables used to change target device and emulation
mode so that the `Makefile` doesn't need constantly modified to change
this. If unspecified they default to `hw` and `xilinx_vcu1525_dynamic_5_1`.
Adding notes to `environment.rst` for new environment variables used to
change target device and emulation mode.
> Modifying the Makefile for hw_emu/sw_emu

- include/CL/sycl/parallelism/detail/parallelism.hpp
- tests/parallel_for/CMakeLists.txt
- tests/parallel_for/hierarchical.cpp
- tests/parallel_for/hierarchical_new.cpp
I replaced the older OpenMP modulo/divison loop with a suggested newer 
implementation that uses OpenMP to collapse nested loops of different 
dimensions and uses constexpr to compile the appropriate one.
I think constexpr is cleaner than having several template 
specializations for each loop in this case.  
Related to triSYCL issue: https://github.com/triSYCL/triSYCL/issues/43
> Refactored `parallel_for_workitem()` implementation

- include/CL/sycl/vec.hpp
Modifying accessors of type x() const {} to be const x() const {} and 
adding accessors of type x() {}, which should cover the two use cases 
for swizzles.
> Additional vec accessor overloads

- tests/device_compiler/buffer_of_objects_member_functions.cpp
- tests/device_compiler/buffer_of_objects_members.cpp
- tests/device_compiler/parallel_for_class_ctor_and_dtor.cpp
- tests/device_compiler/single_task_class_ctor_and_dtor.cpp
Several new device compiler tests that work with POCL when they're
compiled using a newer version of the triSYCL device compiler (after the
commit: [OpenCL] Add generic AS to 'this' pointer).
However, the buffer_of_objects_members.cpp test works with the
sycl/release_70/master branch of the triSYCL device compiler.
The buffer of objects tests are related to:
https://github.com/triSYCL/triSYCL/issues/212
The ctor_and_dtor tests are related to:
https://github.com/triSYCL/triSYCL/issues/213
> Additional Device Compiler Tests

- include/CL/sycl/buffer.hpp
Fix to something I broke in a prior patch that was causing build/compile 
errors for tests in the SYCLParallelSTL.
Didn't account for the need to remove the reference on the rvalue 
referenced iterator when passed in, so the iterator_traits class could 
not find the value_type member!
One of those little hard to catch move/reference semantic errors.
Also some minor spelling fixes.
> set_final_data overload fix

- cmake/FindTriSYCL.cmake
Explicit data type must be specified when setting a value into cache in order to avoid implicit conversions that trigger warnings like this:
```
CMake Warning (dev) at cmake/FindTriSYCL.cmake:138 (set):
implicitly converting 'VERSION' to 'STRING' type.
Call Stack (most recent call first):
CMakeLists.txt:13 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
> Fix CMake implicit conversion warning

- cmake/FindTriSYCL.cmake
This PR removes from the `FindTriSYCL.cmake` finder all usages of globally scoped CMake directives like:
```cmake
add_compile_options("-std=c++1z")
```
For instance, the previous one made *all* the compilers used by the client CMake project (after performing  the call to `find_package(triSYCL)`) to have the `-std=c++1z` flag set: e.g. `nvcc` ends up failing because of that unknown flag: 
```cmake
project(test LANGUAGES CXX C FORTRAN CUDA)
find_package(triSYCL REQUIRED)  # -std=c++1z added to all enabled compilers
add_executable(cxx_test test.cpp) # builds with 'g++ -std=c++1z' → OK
add_executable(cu_test test.cu) # builds with 'nvcc -std=c++1z' → ERROR
add_executable(c_test test.c) # builds with 'gcc -std=c++1z' → ERROR
add_executable(f_test test.f90) # builds with 'gfortran -std=c++1z' → …
```
> Isolate cxx build settings into interface target

- README.rst
- doc/about-sycl.rst
- doc/possible-futures.rst
Modernize descriptions.
More content about hipSYCL project and CUDA.
The Khronos SYCL CTS is now open-source.
Add link to Intel SYCL open-source implementation.
Add link to triSYCL + Intel SYCL fusion .
> Update the documentation

- CMakeLists.txt
This is a super minor improvement: using CPack automatically creates the `BUILD_TESTING` option in CMake, which is `ON` by default. If this is explicitly turned off, there's no reason to compile all the tests, which can take quite a long time to compile. This lets users (like me) do a `make install` without the need to compile things I don't care about in certain situations.
> only build tests subdirectory if BUILD_TESTING is enabled

- include/triSYCL/buffer/detail/buffer.hpp
- include/triSYCL/command_group/detail/task.hpp
C++17 allows now std::move capture.
C++20 deprecated implicit capture of "this", so add some explicit captures.
> Update lambda captures to C++17 and C++20

- include/CL/sycl.hpp
- include/SYCL/sycl.hpp
Declare ::cl and ::cl::sycl in a different way.
This should fix https://github.com/triSYCL/triSYCL/issues/256 in case
there is already an existing ::cl::sycl or ::sycl
This sounds like a better neighborhood behavior.
> Make the definition of alternate namespace more liberal

- include/triSYCL/detail/alignment_helper.hpp
- include/triSYCL/rounding_mode.hpp
- include/triSYCL/vec.hpp
- include/triSYCL/vec/detail/vec.hpp
- tests/Makefile
- tests/vector/CMakeLists.txt
- tests/vector/vec_structured_binding.cpp
This should close the extension request https://github.com/triSYCL/triSYCL/issues/271
> Implement SYCL extension for sycl::vec<> with structure binding

- include/triSYCL/detail/instantiate_kernel.hpp
Instead of using the GNU style `__attribute__` we should rely on the standard C++ attribute syntax. This makes things more portable since any C++17 conforming compiler will ignore unknown attributes, thus preventing issues as noted in #269. 
This PR should fix the issues mentioned in #269. In the long-term it might make sense to use clang's OpenCL attributes (`clang::opencl_global`) for address spaces but that would require a more extensive rework of the current address space implementation.
> Use standard C++ attribute syntax

- CMakeLists.txt
- cmake/FindTriSYCL.cmake
- cmake/FindtriSYCL.cmake
- doc/cmake.rst
- doc/testing.rst
Modernize the CMake configuration so it can be used remotely for testing.
See https://github.com/keryell/muSYCL for an example.
This is a WIP since there are some lacking libraries in the CMake configuration, according to https://github.com/triSYCL/triSYCL/issues/285, https://github.com/triSYCL/triSYCL/issues/283, https://github.com/triSYCL/triSYCL/issues/284.
> CMake improvement

- include/triSYCL/math.hpp
Avoid to copy `sycl::vec` arguments for example.
Avoid some warnings from https://github.com/triSYCL/path_tracer
> Add "const &" to math function arguments

- include/triSYCL/detail/debug.hpp
- include/triSYCL/detail/small_array.hpp
- include/triSYCL/kernel/detail/opencl_kernel.hpp
The trisycl::detail::debug CRTP was using introspection of the native
type to know whether the type was copy and move constructible before
defining such a constructor to avoid preventing the generation of the
default assignment operator.
But actually this is an unsolvable question because of the
self-reference essence of the CRTP.
It was still working with G++ but no longer working starting with
Clang++-11.
So, instead, do not use std::enable_if or concepts but just define all
the operators.
A nice side effect is that now copy and move assignments can be traced
too.
> Improve debug tracing class

- include/triSYCL/math.hpp
- include/triSYCL/vec/detail/vec.hpp
- tests/math/vector_math.cpp
Test that sycl::abs now works for sycl::vec.
This should be tested quite more...
This is adds a little bit to https://github.com/triSYCL/triSYCL/issues/40
>  Generalize mathematical functions on sycl::vec

- CMakeLists.txt
- cmake/FindtriSYCL.cmake
- doc/testing.rst
This avoids some issues with old versions provided as package by some Linux distributions.
Also freeze the version of mdspan used to avoid some random breakage if the API changes upstream.
> Fetch the content of the range-v3 library directly from the source

- include/triSYCL/detail/shared_ptr_implementation.hpp
- tests/jacobi/include/stencil-var.hpp
Follow WG21 P1601R0 "Recommendations for Specifying “Hidden Friends”"
from Walter E. Brown & Daniel Sunderland.
This removes compilation warnings like:
```c++
.../triSYCL/include/triSYCL/device_selector/detail/device_selector_tail.hpp:98:18: warning:
ISO C++20 considers use of overloaded operator '==' (with operand types 'const trisycl::device' and
'const trisycl::device') to be ambiguous despite there being a unique best viable function
[-Wambiguous-reversed-operator]
return dev == default_device ? 1 : -1;
```
Also remove a useless capture of `this`.
> Use hidden friend comparison operators instead of member functions

- include/triSYCL/accessor/mixin/accessor.hpp
- include/triSYCL/buffer/detail/buffer.hpp
Follow latest `mdspan` implementing https://isocpp.org/files/papers/P2299R3.html so the usage is simplified.
`mdspan` implementation has renamed `pointer` and `data()` members.
Use `data_handle_type` and `data_handle()` instead.
> Update to mdspan P0009r17 proposing now dextents

- include/triSYCL/handler.hpp
- include/triSYCL/range.hpp
After generalizing the code for any dimension, some default paths were
wrongly used when using sycl::kernel instead of kernel callable.
> Avoid derailing the sycl::kernel into the generic parallel_for

- CMakeLists.txt
- cmake/FindtriSYCL.cmake
- include/CL/sycl.hpp
- include/sycl/sycl.hpp
- include/triSYCL/accessor.hpp
- include/triSYCL/accessor/facade/accessor.hpp
- include/triSYCL/accessor/mixin/accessor.hpp
- include/triSYCL/detail/array_tuple_helpers.hpp
- include/triSYCL/detail/global_config.hpp
- include/triSYCL/detail/small_array.hpp
- include/triSYCL/id.hpp
- tests/address_spaces/address_spaces_pstl.cpp
- tests/common/test-helpers.hpp
- tests/id/CMakeLists.txt
- tests/id/id_any_dimension.cpp
- tests/id/tuple_like_protocol.cpp
- tests/parallel_for/CMakeLists.txt
- tests/parallel_for/generalized_dimension.cpp
- tests/range/CMakeLists.txt
- tests/range/tuple_like_protocol.cpp
Now it is possible to write code like:
```c++
int main() {
{
sycl::queue q;
sycl::buffer<int, 4> a { { 2, 3, 5, 7 } };
q.submit([&](sycl::handler& cgh) {
sycl::accessor acc { a, cgh };
cgh.parallel_for(a.get_range(), [=](sycl::id<4> i) {
auto [x, y, z, t] = i;
acc[x, y, z, t] = x + y + z + t;
});
});
VERIFY_BUFFER_VALUE(a, [](sycl::id<4> i) { return i[0] + i[1] + i[2] + i[3]; });
return 0;
}
}
```
> Add C++23 mdspan-like indexing and tuple protocol on accessors

- .github/workflows/cmake.yml
- .github/workflows/run_ci_in_docker.bash
- include/triSYCL/accessor/mixin/accessor.hpp
- include/triSYCL/buffer/detail/accessor.hpp
- tests/math/vector_math.cpp
Clang 15 crashes on the code, so use a distribution providing a more modern version.
Actually the bug was only fixed recently with https://reviews.llvm.org/D149637 and https://reviews.llvm.org/D150008.
Also update `mdspan` namespace to remove `experimental::` now it landed in C++23.
> Use Ubuntu 23.04, Clang 17 ToT and update for latest mdspan

- .github/workflows/cmake.yml
Update to latest https://github.com/actions/checkout to remove these warnings:
```
Annotations
5 warnings
CMake with default option on the default GitHub Ubuntu
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
> GitHub actions moved to actions/checkout@v3

- .github/workflows/cmake.yml
The problem is when the CI compilation time does not fit into the
default GitHub limits, the job is killed and ccache action cannot even
save its compilation cache for next CI execution.
So add an optional timeout usable from the manual launch to stop the
compilation before the deadline so ccache can save the partial compilation.
Also add some output about the execution context to help debug.
Rename clang-17 to clang-18 since there is a release process starting.
> Add compilation timeout for partial compilation to ccache

- include/triSYCL/detail/small_array.hpp
Does not allow only for underlying std::size_t.
This allows for example to execute a kernel taking an int as an id instead of a sycl::id<1> or a std::size_t.
> Allow conversion of 1D small array to any integral type
